### ISSUE TITLE
Pin firefox version to betterfox version

### ISSUE THREAD

**Issue by CountingBeeps** [HeitorAugustoLN/betterfox-nix#6]
First, thanks for making this.

I don't want to have to manually update the betterfox version every time firefox updates, so I have it set to main. This leads to this message on rebuild:

> evaluation warning: ethan profile: Betterfox version main does not match Firefox's (131.0.2)

It would be really nice if there was a way to pin one's version to the other so they always match.

**Comment by HeitorAugustoLN** [comment]
I don't really know if this is possible, since I don't wanna mess with what packages users using. And this would add multiple nixpkgs, which would get some big storage. But this warning is not something that you should worry about, it is just to remember the user to update betterfox-nix, if a new betterfox version is available. But it don't work as it should as of now, I will update it soon, to only warn if it has a updated version in the repo.

**Comment by GameDungeon** [comment]
I'm not worried about the warning really. Just wanted a way to get rid of it. Maybe it should be disabled if you don't set a specific version? It would be pretty safe to assume both were at the latest then.

**Comment by HeitorAugustoLN** [comment]
> I'm not worried about the warning really. Just wanted a way to get rid of it. Maybe it should be disabled if you don't set a specific version? It would be pretty safe to assume both were at the latest then.

I will remove it for main specifically, I don't really know why I don't removed it before.
